# Generated by Django 2.2.16 on 2022-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220915_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username1111', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
