# Generated by Django 2.2.16 on 2022-09-18 06:26

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220917_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория произведения', 'verbose_name_plural': 'Категории произведений'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр произведения', 'verbose_name_plural': 'Жанры произведений'},
        ),
        migrations.AlterModelOptions(
            name='genretitle',
            options={'ordering': ['title'], 'verbose_name': 'Связь произведения и жанра', 'verbose_name_plural': 'Связь произведений и жанров'},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=4, validators=[reviews.validators.validate_year]),
        ),
    ]
