# Generated by Django 2.2.16 on 2022-09-18 06:32

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220918_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.FloatField(validators=[reviews.validators.validate_year]),
        ),
    ]
