# Generated by Django 2.2.16 on 2022-09-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220915_0056'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_name_owner',
        ),
    ]
